-- =====================================================================
-- Larnr schema for SQLite (development)
-- Port of database/schema.sql (PostgreSQL) to SQLite dialect.
--   * CHAR(36) UUIDs, generated by the app (Eloquent HasUuids)
--   * CHECK constraints in place of PostgreSQL enums
--   * money stored as integer minor units (cents)
--   * DATETIME stored in UTC, ISO-8601 'YYYY-MM-DD HH:mm:ss'
--   * INTEGER booleans (0/1)
--   * no DB triggers (Eloquent maintains timestamps)
-- Idempotent: safe to run repeatedly.
-- =====================================================================

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id             CHAR(36)     PRIMARY KEY,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(10)  NOT NULL DEFAULT 'STUDENT'
        CHECK (role IN ('STUDENT', 'TUTOR', 'ADMIN')),
    is_active      INTEGER      NOT NULL DEFAULT 1
        CHECK (is_active IN (0, 1)),
    base_currency  VARCHAR(3)   NOT NULL DEFAULT 'USD',
    remember_token VARCHAR(100) NULL,
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_profiles (
    user_id      CHAR(36)     PRIMARY KEY,
    full_name    VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30)  NULL,
    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tutor_profiles (
    user_id          CHAR(36)     PRIMARY KEY,
    full_name        VARCHAR(255) NOT NULL,
    headline         VARCHAR(255) NULL,
    bio              TEXT         NULL,
    hourly_rate      INTEGER      NOT NULL DEFAULT 0
        CHECK (hourly_rate >= 0),
    currency         VARCHAR(3)   NOT NULL DEFAULT 'USD',
    is_verified      INTEGER      NOT NULL DEFAULT 0
        CHECK (is_verified IN (0, 1)),
    city             VARCHAR(100) NULL,
    format           VARCHAR(20)  NOT NULL DEFAULT 'ONLINE'
        CHECK (format IN ('ONLINE', 'IN_PERSON', 'BOTH')),
    experience_level VARCHAR(10)  NOT NULL DEFAULT 'ENTRY'
        CHECK (experience_level IN ('ENTRY', 'MID', 'SENIOR')),
    rating           REAL         NOT NULL DEFAULT 0.0
        CHECK (rating >= 0 AND rating <= 5),
    avatar_url       VARCHAR(500) NULL,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subjects (
    id         CHAR(36)     PRIMARY KEY,
    name       VARCHAR(150) NOT NULL UNIQUE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tutor_subjects (
    tutor_id   CHAR(36) NOT NULL,
    subject_id CHAR(36) NOT NULL,
    rate_cents INTEGER  NOT NULL DEFAULT 0
        CHECK (rate_cents >= 0),
    PRIMARY KEY (tutor_id, subject_id),
    FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS availability_slots (
    id         CHAR(36) PRIMARY KEY,
    tutor_id   CHAR(36) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time   DATETIME NOT NULL,
    is_booked  INTEGER  NOT NULL DEFAULT 0
        CHECK (is_booked IN (0, 1)),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
    CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_availability_tutor_time
    ON availability_slots (tutor_id, start_time);

CREATE TABLE IF NOT EXISTS bookings (
    id               CHAR(36)     PRIMARY KEY,
    student_id       CHAR(36)     NOT NULL,
    tutor_id         CHAR(36)     NOT NULL,
    subject_id       CHAR(36)     NULL,
    slot_id          CHAR(36)     NULL,
    scheduled_at     DATETIME     NULL,
    duration_minutes INTEGER      NOT NULL DEFAULT 60
        CHECK (duration_minutes > 0),
    amount           INTEGER      NOT NULL DEFAULT 0
        CHECK (amount >= 0),
    currency         VARCHAR(3)   NOT NULL DEFAULT 'USD',
    status           VARCHAR(30)  NOT NULL DEFAULT 'PENDING_PAYMENT'
        CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'DISPUTED')),
    notes            TEXT         NULL,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE SET NULL,
    FOREIGN KEY (slot_id) REFERENCES availability_slots (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_bookings_student ON bookings (student_id);
CREATE INDEX IF NOT EXISTS idx_bookings_tutor ON bookings (tutor_id);

CREATE TABLE IF NOT EXISTS transactions (
    id                       CHAR(36)     PRIMARY KEY,
    booking_id               CHAR(36)     NOT NULL,
    type                     VARCHAR(30)  NOT NULL
        CHECK (type IN ('LESSON_PAYMENT', 'ESCROW_RELEASE', 'REFUND', 'PLATFORM_FEE')),
    amount                   INTEGER      NOT NULL
        CHECK (amount >= 0),
    currency                 VARCHAR(3)   NOT NULL DEFAULT 'USD',
    status                   VARCHAR(20)  NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    platform_fee             INTEGER      NOT NULL DEFAULT 0
        CHECK (platform_fee >= 0),
    stripe_payment_intent_id VARCHAR(255) NULL,
    created_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transactions_booking ON transactions (booking_id);

CREATE TABLE IF NOT EXISTS tutor_profile_reviews (
    id               CHAR(36)     PRIMARY KEY,
    tutor_id         CHAR(36)     NOT NULL,
    full_name        VARCHAR(255) NULL,
    headline         VARCHAR(255) NULL,
    bio              TEXT         NULL,
    hourly_rate      INTEGER      NULL
        CHECK (hourly_rate IS NULL OR hourly_rate >= 0),
    currency         VARCHAR(3)   NULL,
    city             VARCHAR(100) NULL,
    format           VARCHAR(20)  NULL
        CHECK (format IS NULL OR format IN ('ONLINE', 'IN_PERSON', 'BOTH')),
    experience_level VARCHAR(10)  NULL
        CHECK (experience_level IS NULL OR experience_level IN ('ENTRY', 'MID', 'SENIOR')),
    avatar_url       VARCHAR(500) NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reviewed_by      CHAR(36)     NULL,
    reviewed_at      DATETIME     NULL,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tpr_tutor_status ON tutor_profile_reviews (tutor_id, status);

CREATE TABLE IF NOT EXISTS user_activities (
    id          CHAR(36)     PRIMARY KEY,
    user_id     CHAR(36)     NOT NULL,
    type        VARCHAR(40)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    ip_address  VARCHAR(45)  NULL,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_activities_user_time
    ON user_activities (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_user_activities_created
    ON user_activities (created_at);
